module.exports = {

    MESAJ_GONDERIM_SURESI: 10,
    CHANNEL_ID: "1163493454341480532",

    TOKENLER: ["MTE1MzYwMjAxODQ0Nzk5OTA5OA.GbJCOB.0964xnrZggu7x0J6fA15W1K4lwnWs2DP7WntRU",

    ],


    KELIMELER: [
        "#OLAĞANÜSTÜ EFSANEVİ MUAZZAM YÜCE GÖRKEMİM VE IŞILTILI DASİTANİ İHTİŞAMIM KARŞISINDA MAHÇUP DÜŞEN GÖZLERİ KAMAŞAN KÜÇÜK DİLİNİ YUTAN ELİ AYAĞINA DOLAŞAN NUTKU TUTULAN GOSEVİLDE KARICIĞIM. SAKSOCU ETKİSİZ ELEMAN ÇARIKLI FAN GİRL'S EFORSUZ PESPAYE PEJMÜRDE YAMYAM SHREK GUDUBET ÇİÇEĞİ BURNUNDA ANKSİYETE KAPILMA RADDESİNE GELMİŞ KEÇİLERİNİ KAÇIRMIŞ AKILDAN NOKSAN KITKANAAT KÜLFETLİ ZAİYAT YILAN GİBİ DERİ DEĞİŞTİREN SEMENDER KENDİNİ PARALAYAN ÜÇ KURUŞLUK METANETSİZ ÇİRKİNLİK AĞACINDAN DÜŞMÜŞ LEVOSSED EKMEK TEKNESİ SİRK MAYMUNU CEHENNEM ODUNU ÖLÜM KORKUSUNA GEM VURAMAMIŞ NAMERT LEKESİZ GÜNAH HAVARİSİ MELAMET HIRKASI GİYMİŞ KARA CAHİL ABLAVUT JEBBY AÇIKGÖZLÜ HYPSİLOPHODON KEMİK TORBASI NEFRET TOHUMU STOORİSH TSUMİBİTO KÖHNELEŞMİŞ HORTLAK MELUN BENEKLİ DEYYUS ÇİRKİN ŞİRRET CADI BAİSHUNPU ZEVKSİZ GECENİN MAHSÜLÜ DOĞUM LEKELİ ÇİFT YUMURTA İKİZİ LANET GURMESİ TASMANİA MONSTER PERİ BACALARI KAPLICASI KISRAK KİKAJOY SEXS ABİDESİ CÜRMÜ AŞK MUSİBETİ VAFTİZ ÇOCUĞU MAYMUNDAN BEŞ DAKİKA ÖNCE DOĞMUŞ HİLKAT GARİBESİ AĞUSTOS BÖCEĞİ SÜT ÇOCUĞU BOYNUZLU ANAKONDA GRANNY YEDİ BAŞLI YILAN  TELETABİ CHARACTER OKAMA ŞİRRET ZAMPARA VİLLİAN CANDOM ZOMBİE CARTLAK ACUZE METELİKSİZ MORON TORTLU KALTABAN KÜÇÜK ÇAPLI ÜRETİM HATASI UNSAFE FANCAM GOSEVİLDE ELLERİN AYAKLARIN BAĞLANDI KAS KATI KESİLDİN AKIBETİNİ TALAN EDECEĞİM YAĞMALAYACAĞIM DEFTERİN DÜRÜLDÜ DÜNYA'DAN GÖÇME VAKTİN GELDİ ÖLÜM YAPRAĞIN DALINDAN KOPTU SENİN BEKARETİNİ ELİNDEN ALDIM BAKİRELİĞİNİ BOZDUM YENİ YETİŞMİŞ TOMURCUKLANMIŞ KIZLIK ZARINI PARÇALADIM ALABORA ETTİM ALTINI ÜSTÜNE GETİRDİM GÜNAHININ KEFARETİNİ AĞIR ÖDEDİN KÖTÜ EMELLERİME ALET OLDUN SİKE SİKE SONSUZ SADAKAT YEMİNİ ETTİRDİĞİM VELETLER ALAŞAĞI EDİLMİŞTİR GÖZDAĞI VERİLMİŞTİR BENİ GÖRDÜĞÜ HER YERDE KAÇACAK DELİK ARAYAN GÖT KORKUSUNDAN İKİ BÜKLÜM OLAN  LEVOSSED & GOSEVİLDE VÜCUDUNUN HER GÖZENEĞİNDE DEVASA GEDİKLER AÇTIM ARE YOU READY TO DİE ? @everyone",



    ]

}
